# Generated by Django 3.0.3 on 2020-03-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200306_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfimString',
            new_name='ConfirmString',
        ),
    ]
